### ISSUE TITLE
[USA] Virginia Beach-Norfolk-VA-NC roads dataset 

### ISSUE THREAD

**Issue by arming-telenav** [TelenavMapping/External_Data#122]
We are considering using this dataset for our future edits in Virginia Beach metro area:

[Virginia State road centerline dataset](https://vgin.maps.arcgis.com/home/item.html?id=cd9bed71346d4476a0a08d3685cb36ae)

License type - unknown

![image](https://user-images.githubusercontent.com/24649532/42680051-8b874186-868c-11e8-864b-c9897802c819.png)

Sent email to data owner to check license compatibility.

**Comment by arming-telenav** [comment]
Received reply from data owner:


We have language on the AGOL / Clearinghouse RCL page which states that we do not warrant the accuracy of the dataset and **that the data is public domain as of 2012**.  We have also sent this information to OSM in the past unlicensed and the page in itself is a download page. 

Thanks,
Joe

**Comment by ArminGheorghina2** [comment]
The local data file was processed with [Cygnus ](http://cygnus.improve-osm.org/add;jsessionid=a0syegaektpo1qxcxufox6wnn?0 )resulting 72.809 mi of roads that did not have names in OSM but had names in the local data file. These roads have been reviewed, and for 65% (47 mi) the names have been added. The remaining 35% (25 mi) consisted of false positives, or cases where local data was inconclusive, and have been skipped.
